<?php
/**
 * @file
 * Define the database schema and update functions for the database server module.
 */

/**
 * Implements hook_schema().
 */
function hosting_db_server_schema() {
  $schema['hosting_db_server'] = array(
    'fields' => array(
      'vid' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'nid' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'db_user' => array(
        'type' => 'text',
        'size' => 'big',
        'default' => NULL,
      ),
      'db_passwd' => array(
        'type' => 'text',
        'size' => 'big',
        'default' => NULL,
      ),
    ),
    'primary key' => array('vid'),
  );

  return $schema;
}

/**
 * Allow the db_user and db_passwd column to be NULL (for localhost)
 */
function hosting_db_server_update_1000() {
  db_query('ALTER TABLE hosting_db_server CHANGE db_user db_user TEXT DEFAULT NULL');
  db_query('ALTER TABLE hosting_db_server CHANGE db_passwd db_passwd TEXT DEFAULT NULL');
}
