<?php
/**
 * @file
 * Define database schema and update functions for the Platforms module.
 */

/**
 * Implements hook_install() for Backdrop
 */
function hosting_platform_install() {
  if (!defined('BACKDROP_ROOT')) {
    return;
  }
  // See https://docs.backdropcms.org/change-records/hook_node_info-removed
  $type = [
    "type" => 'platform',
    "name" => 'Platform',
    'base' => 'hosting_platform',
    "has_title" => TRUE,
    "title_label" => t('Name'),
    "description" => t("<strong>The file system location on a specific web server on which to publish sites.</strong>\nMultiple platforms can co-exist on the same web server, and need to do so for upgrades to be managed, as this is accomplished by migrating the site between platforms. Platforms are most commonly built for specific releases of Drupal."),
    "has_body" => 0,
    "body_label" => '',
    "min_word_count" => 0,
    // Lock the machine name
    'locked' => TRUE,
  ];
  $type = node_type_set_defaults($type);
  node_type_save($type);
}

/**
 * Implements hook_schema().
 */
function hosting_platform_schema() {
  $schema['hosting_platform'] = [
    'fields' => [
      'vid' => [
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ],
      'nid' => [
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ],
      'publish_path' => [
        'type' => 'text',
        'size' => 'normal',
        'not null' => FALSE,
      ],
      'software' => [
        'type' => 'text',
        'size' => 'tiny',
        'default' => NULL,
      ],
      'phpversion' => [
        'type' => 'text',
        'size' => 'tiny',
        'default' => NULL,
      ],
      'web_server' => [
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ],
      'verified' => [
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ],
      'status' => [
        'type' => 'int',
        'size' => 'tiny',
        'not null' => TRUE,
        'default' => 0,
      ],
      'site_post_install_cmd' => [
        'type' => 'text',
        'size' => 'big',
        'default' => NULL,
      ],
      'site_post_import_cmd' => [
        'type' => 'text',
        'size' => 'normal',
        'default' => NULL,
      ],
      'site_post_verify_cmd' => [
        'type' => 'text',
        'size' => 'normal',
        'default' => NULL,
      ],
    ],
    'primary key' => ['vid'],
  ];

  return $schema;
}

/**
 * Add the software column, remove makefile and make_working_copy
 */
function hosting_platform_update_7500() {
  if (!db_field_exists('hosting_platform', 'software')) {
    db_add_field('hosting_platform', 'software', [
      'type' => 'text',
      'size' => 'big',
      'default' => NULL,
    ]);
  }
  if (db_field_exists('hosting_platform', 'makefile')) {
    db_drop_field('hosting_platform', 'makefile');
    db_drop_field('hosting_platform', 'make_working_copy');
  }
}

/**
 * Add the site_post_install_cmd, import, verify columns
 */
function hosting_platform_update_7501() {
  if (!db_field_exists('hosting_platform', 'site_post_install_cmd')) {
    db_add_field('hosting_platform', 'site_post_install_cmd', [
      'type' => 'text',
      'size' => 'big',
      'default' => NULL,
    ]);
  }
  if (!db_field_exists('hosting_platform', 'site_post_import_cmd')) {
    db_add_field('hosting_platform', 'site_post_import_cmd', [
      'type' => 'text',
      'size' => 'big',
      'default' => NULL,
    ]);
  }
  if (!db_field_exists('hosting_platform', 'site_post_verify_cmd')) {
    db_add_field('hosting_platform', 'site_post_verify_cmd', [
      'type' => 'text',
      'size' => 'big',
      'default' => NULL,
    ]);
  }
}

/**
 * Import the Views configuration during D7 to Backdrop upgrade.
 */
function hosting_platform_update_1000() {
  config_install_default_config('hosting_platform', 'views.view.hosting_platform_list');
}

/**
 * Add the phpversion field
 */
function hosting_platform_update_1001() {
  if (!db_field_exists('hosting_platform', 'phpversion')) {
    db_add_field('hosting_platform', 'phpversion', [
      'type' => 'text',
      'size' => 'tiny',
      'default' => NULL,
    ]);
  }
}
