<?php
/**
 * @file
 * Web server node type is defined here.
 */

/**
 * Implements hook_autoload_info() for Backdrop.
 */
function hosting_web_server_autoload_info() {
  return [
    'hostingService_http_public' => 'hosting_web_server.service.inc',
    'hostingService_http_apache' => 'hosting_web_server.service.inc',
  ];
}

/**
 * Implements hook_hosting_service().
 */
function hosting_web_server_hosting_service() {
  return array(
    'apache' => 'http',
  );
}

/**
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function hosting_web_server_hosting_service_type() {
  return array(
    'http' => array(
      'title' => t('Web'),
    ),
  );
}

