<?php
/**
 * @file
 * Install, update and uninstall functions for the hosting_queued module.
 *
 */

/**
 * Implements hook_enable().
 */
function hosting_queued_enable() {
  // Disable Aegir's dispatch of the tasks queue.
  variable_set('hosting_queue_tasks_enabled', FALSE);
}

/**
 * Implements hook_disable().
 */
function hosting_queued_disable() {
  // Enable Aegir's dispatch of the tasks queue.
  variable_set('hosting_queue_tasks_enabled', TRUE);
}
