<?php

/**
 * Implements hook_menu().
 */
function hosting_usage_menu() {
  $items = [];

  $items['hosting/usage'] = [
    'page callback' => 'hosting_usage_page',
    'type' => MENU_CALLBACK,
    'access arguments' => ['administer hosting'],
  ];

  return $items;
}

/**
 * Page callback to display site usage stats.
 */
function hosting_usage_page() {
  $header = [
    'site' => ['data' => t('Site')],
    'DirSize' => ['data' => t('Files Usage')],
    'DatSize' => ['data' => t('SQL Usage')],
    'CiviContact' => ['data' => t('Contacts')],
    'CiviActivity' => ['data' => t('Activities')],
    'CiviContribute' => ['data' => t('Contributions')],
    'CiviMember' => ['data' => t('Memberships')],
    'CiviMail' => ['data' => t('Mailings')],
    'CiviSms' => ['data' => t('SMS')],
    'CiviCase' => ['data' => t('Cases')],
    'CiviEvent' => ['data' => t('Events')],
    'CiviParticipant' => ['data' => t('Participants')],
    'CiviPaymentProcessors' => ['data' => t('Payment Processors')],
    'CiviLanguages' => ['data' => t('Languages')],
    'LastLogin' => ['data' => t('Last Login')],
    'Created' => ['data' => t('Created')],
  ];

  if (!file_exists('/var/log/aegir/usage.log')) {
    return t('The usage.log is not available. Please check that the weekly.sh script is running.');
  }

  $rows = hosting_usage_get_data();

  // Add the creation date
  foreach ($rows as $site => $data) {
    $node = hosting_get_site_by_url($site);
    $rows[$site]['created'] = date('Y-m-d', $node->created);
  }

  $render['usage'] = [
    '#theme' => 'table',
    '#header' => $header,
    '#rows' => $rows,
  ];

  return $render;
}

/**
 * Load /var/log/aegir/usage.log, if it exists, so that stats can be displayed
 * in the inventory (picked up by telemetrie via hosting_civicrm_ansible).
 */
function hosting_usage_get_data() {
  $handle = fopen('/var/log/aegir/usage.log', 'r');
  $rows = [];

  if ($handle === FALSE) {
    throw new Exception(t('The usage.log cannot be read. Please check file permissions on the server.'));
  }

  while (($data = fgetcsv($handle, NULL, ',')) !== FALSE) {
    if (count($data) < 2) {
      continue;
    }

    $site = $data[1];

    if (!isset($rows[$site])) {
      $rows[$site] = [];
      $rows[$site]['site'] = $site;
    }

    list($col, $val) = explode(':', $data[2]);

    if (!$val) {
      $val = '';
    }

    $rows[$site][$col] = $val;
  }

  return $rows;
}
